### ISSUE TITLE
Del/addtime usable without @

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#40]
Make the deltime and addtime command be usable without having to tag a user so we're able to use it on untagable users or we're able to use it without disturbing people with pings.

**Comment by pianiststickman** [comment]
I thought about doing this when I did 3rd party stats. I decided against it because:

1) only bot managers can use the command
2) if the command is being used, it's probably in reference to a current conversation that the user is already a part of, which means they're not really being disturbed

Note that untaggable users are still taggable with `<@id>`. Given the above I'm not really sure if we need `addtime`/`deltime` to function the same way.

**Comment by pianiststickman** [comment]
Bot Managers can also execute commands in #staff-room without pinging users.
